Resources:
  DB:
   Type: "AWS::RDS::DBInstance"
   Properties:
    AllocatedStorage: 5
    StorageType: gp2
    DBInstanceClass: db.t2.micro
    DBName: # Your DB Name
    Engine: MySQL
    MasterUsername: # Your Master Username
    MasterUserPassword: # Your Master Password
  EC2:
   Type: "AWS::EC2::Instance"
   Properties:
    ImageId: ami-1853ac65 # us-east-1 sept 2017
    InstanceType: t2.micro
  S3:
    Type: "AWS::S3::Bucket"
    Properties:
     BucketName: wp-xxxxxx # Replace xxxxxx with random string (lowercase)