Parameters:
 EnvironmentSize:
  Type: String
  Default: Small
  AllowedValues:
   - Small
   - Medium
   - Large
  Description: Select Environment Size (Small, Medium, Large)
 DatabaseName:
  Type: String
 DatabaseUser:
  Type: String
 DatabasePassword:
  Type: String
  NoEcho: true
Mappings:
 RegionMap:
  us-east-1: # Northern Virginia
   "AMALINUX" : "ami-1853ac65" # AMALINUX Sept 2017
  us-east-2: # Ohio
   "AMALINUX" : "ami-25615740" # AMALINUX Sept 2017
  us-west-1: # Northern California
   "AMALINUX" : "ami-bf5540df" # AMALINUX Sept 2017
  us-west-2: # Oregon
   "AMALINUX" : "ami-d874e0a0" # AMALINUX Sept 2017
  ap-south-1: # Mumbai
   "AMALINUX" : "ami-7c87d913" # AMALINUX Sept 2017
  ap-northeast-2: # Seoul
   "AMALINUX" : "ami-5e1ab730" # AMALINUX Sept 2017
  ap-southeast-1: # Singapore
   "AMALINUX" : "ami-e2adf99e" # AMALINUX Sept 2017
  ap-southeast-2: # Sydney
   "AMALINUX" : "ami-43874721" # AMALINUX Sept 2017
  ap-northeast-1: # Tokyo
   "AMALINUX" : "ami-a77c30c1" # AMALINUX Sept 2017
  ca-central-1: # Canada (Central)
   "AMALINUX" : "ami-5b55d23f" # AMALINUX Sept 2017
  eu-central-1: # Frankfurt
   "AMALINUX" : "ami-ac442ac3" # AMALINUX Sept 2017
  eu-west-1: # Ireland
   "AMALINUX" : "ami-3bfab942" # AMALINUX Sept 2017
  eu-west-2: # London
   "AMALINUX" : "ami-dff017b8" # AMALINUX Sept 2017
  eu-west-3: # Paris
   "AMALINUX" : "ami-4f55e332" # AMALINUX Sept 2017
  sa-east-1: # Sao Polo
   "AMALINUX" : "ami-5339733f" # AMALINUX Sept 2017
 InstanceSize:
  Small:
   "EC2" : "t2.micro"
   "DB" : "db.t2.micro"
  Medium:
   "EC2" : "t2.small"
   "DB" : "db.t2.small"
  Large:
   "EC2" : "t2.medium"
   "DB" : "db.t2.medium"
Resources:
 DB:
  Type: "AWS::RDS::DBInstance"
  Properties:
   AllocatedStorage: 5
   DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB] # Dynamic Mapping + Pseudo Parameter
   DBName: !Ref DatabaseName
   Engine: MySQL
   MasterUsername: !Ref DatabaseUser
   MasterUserPassword: !Ref DatabasePassword
 EC2:
  Type: "AWS::EC2::Instance"
  Properties:
   ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX] # Dynamic Mapping + Pseudo Parameter
   InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
   KeyName: EC2Key
   UserData: # Dependency with RDS created with line 89's DB.Endpoint.Address
    "Fn::Base64":
     !Sub |
      #!/bin/bash
      yum install httpd php mysql php-mysql -y
      yum update -y
      chkconfig httpd on
      service httpd start
      cd /var/www/html
      wget https://wordpress.org/latest.tar.gz
      tar -zxvf latest.tar.gz --strip 1
      rm latest.tar.gz
      cp wp-config-sample.php wp-config.php
      sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
      sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
      sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
      sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
 S3:
  Type: "AWS::S3::Bucket"